- examples/qm9/train_qm9.py
In the previous code, `ss = StandardScaler()`, which is not defined in scaling modes other than `'standardize'`, was used in `scaled_abs_error()` and the script crashed there.
This PR fixes this problem by defining `'none'` scaling mode explicitly.
> Enable no standardizing scaling method

- examples/README.md
- examples/example_test_cpu.sh
- examples/example_test_gpu.sh
This PR adds scripts to test code in the example directory.
> Add test scripts for examples

- chainerchem/dataset/preprocessors/weavenet_preprocessor.py
This PR adds a comment on a refactoring idea to `construct_hydrogen_bonding`.
> Add a comment to weavenet preprocessor

- examples/README.md
> fix small typo

- README.md
updated destination URL of LICENSE badge
> update URL for LICENSE

- docs/source/install.rst
> Fix a title underline

- .travis.yml
This PR adds Python 2.7 as a version to test in Travis.
> Add Python 2.7

- README.md
> Fix reference

- .codecov.yml
- .travis.yml
This PR adds [Codecov](https://codecov.io/gh) service to this repository to measure test coverage.
> Add Codecov integration

- README.md
- docs/source/install.rst
- examples/qm9/train_qm9.py
- setup.py
> Add scikit learn as dependency

- tests/iterators_tests/test_balanced_serial_iterator.py
> Add test for balanced serial iterator

- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/parsers/sdf_file_parser.py
- chainer_chemistry/datasets/qm9.py
- chainer_chemistry/datasets/tox21.py
- tests/dataset_tests/parsers_tests/test_csv_file_parser.py
- tests/dataset_tests/parsers_tests/test_sdf_file_parser.py
Please merge it after https://github.com/pfnet-research/chainer-chemistry/pull/79
This PR adds `pytest` for CSVFileParser
> Test csv file parser

- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/preprocessors/__init__.py
- chainer_chemistry/dataset/preprocessors/atomic_number_preprocessor.py
- chainer_chemistry/dataset/preprocessors/ggnn_preprocessor.py
- chainer_chemistry/dataset/preprocessors/nfp_preprocessor.py
- chainer_chemistry/dataset/preprocessors/rsgcn_preprocessor.py
- chainer_chemistry/dataset/preprocessors/schnet_preprocessor.py
- chainer_chemistry/dataset/preprocessors/weavenet_preprocessor.py
- chainer_chemistry/datasets/qm9.py
- chainer_chemistry/iterators/balanced_serial_iterator.py
- chainer_chemistry/links/__init__.py
- chainer_chemistry/links/embed_atom_id.py
- chainer_chemistry/models/__init__.py
- chainer_chemistry/models/ggnn.py
- chainer_chemistry/models/nfp.py
- chainer_chemistry/models/rsgcn.py
- chainer_chemistry/models/weavenet.py
This PR apply autopep8 and flake8 to obey PEP8.
> Apply autopep8 and flake8 to obey PEP8.

- README.md
> Rsgcn readme

- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/parsers/sdf_file_parser.py
- chainer_chemistry/datasets/qm9.py
- chainer_chemistry/datasets/tox21.py
- tests/dataset_tests/parsers_tests/test_csv_file_parser.py
- tests/dataset_tests/parsers_tests/test_sdf_file_parser.py
- tests/dataset_tests/preprocessors_tests/test_atomic_number_preprocessor.py
- tests/dataset_tests/preprocessors_tests/test_nfp_preprocessor.py
- tests/dataset_tests/preprocessors_tests/test_schnet_preprocessor.py
resolve #92 
My main concern is default argument. 
For now, I set True as `return_smiles` default argument.
If you have opinion, please tell me.
> Return dict that contains dataset and smiles from parser.parse

- tests/dataset_tests/preprocessor_tests/test_common.py
> test: add test of case self_connection=False

- examples/tox21/inference_tox21.py
- examples/tox21/predictor.py
- examples/tox21/train_tox21.py
Support `tox21/inference.py` for SchNet
> Schnet predict

- examples/example_test_cpu.sh
- examples/example_test_gpu.sh
- examples/tox21/inference_tox21.py
- examples/tox21/predictor.py
- examples/tox21/train_tox21.py
Please merge this after PR #103 & #104
1. Add RSGCN test
2. Support SchNet tox21/inference.py
3. Add ROCAUCEvaluator test
> Test example update

- chainer_chemistry/dataset/converters.py
This PR adds a document to `concat_mols`
> Add documents to concat_mols

- chainer_chemistry/dataset/preprocessors/rsgcn_preprocessor.py
- chainer_chemistry/models/rsgcn.py
1. update readout activation function, 2. support case when readout is type Link.
See discussion at the end of #89
> Update RSGCN readout

- chainer_chemistry/datasets/qm9.py
- tests/datasets_tests/test_qm9.py
Call sort() to ensure order. 
Also, change loglevel to show message. Add tqdm to show progressbar.
> QM9 dataset ordering

- examples/qm9/qm9_dataset_exploration.ipynb
- examples/tox21/tox21_dataset_exploration.ipynb
This PR adds jupyter notebook for dataset explanation.
You may refer here as well.
https://github.com/corochann/chainer-chemistry/blob/dataset_exploration/examples/qm9/qm9_dataset_exploration.ipynb
https://github.com/corochann/chainer-chemistry/blob/dataset_exploration/examples/tox21/tox21_dataset_exploration.ipynb
> Dataset exploration

- chainer_chemistry/dataset/converters.py
This PR ports the improved document of `concat_examples` of Chainer made in chainer/chainer#4164 to `concat_mols`.
> Improve document of concat_mols

- chainer_chemistry/models/ggnn.py
This PR solves issue #117.
I didn't write a test for this because I will need to modify many parts of existing test. But if I need, I will write a test.
> Fix concat_hidden argument in GGNN

- README.md
- docs/source/index.rst
This PR add an link to an introductory slide (available in google slides) to the document and README.
> Introduction slide

- chainer_chemistry/config.py
- chainer_chemistry/dataset/preprocessors/weavenet_preprocessor.py
- chainer_chemistry/models/weavenet.py
> copy weavenet parameter to config.py

- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/parsers/sdf_file_parser.py
- chainer_chemistry/datasets/qm9.py
- chainer_chemistry/datasets/tox21.py
- tests/dataset_tests/parsers_tests/test_csv_file_parser.py
- tests/dataset_tests/parsers_tests/test_sdf_file_parser.py
Add `target_index` option to enable partial parse
> Parse index

- examples/own_dataset/train.py
- examples/qm9/train_qm9.py
- examples/tox21/train_tox21.py
> Remove matplotlib import from examples

- chainer_chemistry/utils/permutation.py
- tests/models_tests/test_ggnn.py
- tests/models_tests/test_nfp.py
- tests/models_tests/test_schnet.py
- tests/models_tests/test_weavenet.py
- tests/utils_tests/test_permutation.py
The tests in this PR ensures that NFP, Weave, SchNet are graph isormorphism invariant.
> Test graph invariant

- docs/source/models.rst
This PR adds `BaseForwardModel`, `Classifier`, `Regressor` to the document.
> Add wrapper models to the document

- examples/example_test_cpu.sh
- examples/example_test_gpu.sh
- examples/qm9/predict_qm9.py
- examples/tox21/predict_tox21_with_classifier.py
Please merge after #140, #141 
This PR checks the `predict` code introduced in #140, #141 .
> Test predict

- chainer_chemistry/dataset/preprocessors/rsgcn_preprocessor.py
This PR fixes #166 and should be merged after #164.
> NaN values in the adjacency matrix

- chainer_chemistry/dataset/preprocessors/rsgcn_preprocessor.py
- tests/dataset_tests/preprocessors_tests/test_atomic_number_preprocessor.py
- tests/dataset_tests/preprocessors_tests/test_rsgcn_preprocessor.py
This PR adds tests for the RSCN preprocessor and for the non-default `max_atom` and non-default zero padding options.
> Add more preprocessor tests

- chainer_chemistry/datasets/__init__.py
- chainer_chemistry/datasets/molnet/__init__.py
- examples/molnet/train_molnet.py
update init file & apply flake8.
> Molnet init

- examples/molnet/README.md
- examples/molnet/train_molnet.py
Add ROCAUC Evaluator for all classification task.
I confirmed test script runs.
Please merge after https://github.com/pfnet-research/chainer-chemistry/pull/181
> Molnet rocauc classification

- chainer_chemistry/dataset/parsers/__init__.py
- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/parsers/data_frame_parser.py
- tests/dataset_tests/parsers_tests/test_data_frame_parser.py
> DataFrameParser

- chainer_chemistry/datasets/molnet/molnet.py
Rel. #200 
I confirm slow test runs without failure.
> Fix bug in molnet

- chainer_chemistry/dataset/parsers/csv_file_parser.py
- chainer_chemistry/dataset/parsers/smiles_parser.py
- tests/dataset_tests/parsers_tests/test_csv_file_parser.py
- tests/dataset_tests/parsers_tests/test_smiles_parser.py
For CSVFileParser & SmilesParser
> add return_is_successful

- chainer_chemistry/dataset/parsers/sdf_file_parser.py
- tests/dataset_tests/parsers_tests/test_sdf_file_parser.py
This PR 
- add `return_is_successful` option 
- modify `total_count`, `fail_count` behavior
for `SDFFileParser`. Let me discuss the specification before merge.
> add return_is_successful & modify total count behavior

- tests/dataset_tests/splitters_tests/test_stratified_splitter.py
I set strict value. But it fails too much.
> Loosen stratified split test.

- chainer_chemistry/utils/extend.py
- tests/models_tests/test_rsgcn.py
- tests/utils_tests/test_extend.py
This is a test to explicitly check that model forward result is same even if input size is bigger (with atom & adjacency matrix filled with 0).
> Inputsize invariant rsgcn

- chainer_chemistry/datasets/molnet/molnet.py
- tests/datasets_tests/molnet_tests/test_molnet.py
> Fix using frac option in `get_molnet_dataset` function

- chainer_chemistry/dataset/preprocessors/common.py
- chainer_chemistry/dataset/preprocessors/ggnn_preprocessor.py
- chainer_chemistry/utils/extend.py
- tests/dataset_tests/preprocessor_tests/test_common.py
Because this function may be used in other preprocessor.
> moved construct_discrete_edge_matrix to common

- examples/qm9/test_qm9.sh
> examples/qm9/test_qm9.sh: swap parameter position to correctly recognize GPU#0

- chainer_chemistry/models/prediction/base.py
> Rename `device_id` inside `BaseForwardModel`

- chainer_chemistry/models/ggnn.py
- tests/models_tests/test_ggnn.py
I think I need to resolve conflict after #293
> change num_edge_type to be argument

- examples/qm9/evaluate_models_qm9.sh
- examples/qm9/plot.py
- examples/qm9/predict_qm9.py
- examples/qm9/train_qm9.py
bugfix for qm9 example using StandardScaler link
> Fix standard scaling qm9

- examples/qm9/plot.py
- examples/qm9/predict_qm9.py
This PR will change the evaluation behavior of QM9. need review.
> plot result for each label separately

- chainer_chemistry/links/scaler/flow_scaler.py
- tests/links_tests/scaler_tests/test_flow_scaler.py
I am implementing "Flow Scaler", that scale data into the normal distribution.
This Scaler uses a technique named "flow".
> Flow Scaler

- chainer_chemistry/models/gin.py
replace `F.copy` to `functions.copy` in gin.py
> fix gin.py

- README.md
- chainer_chemistry/links/__init__.py
- chainer_chemistry/links/readout/mpnn_readout.py
- chainer_chemistry/links/readout/set2set.py
- chainer_chemistry/links/update/mpnn_update.py
- chainer_chemistry/models/__init__.py
- chainer_chemistry/models/mpnn.py
- tests/links_tests/readout_tests/test_mpnn_readout.py
- tests/links_tests/readout_tests/test_set2set.py
- tests/links_tests/update_tests/test_mpnn_update.py
- tests/models_tests/test_mpnn.py
I add MPNN (https://arxiv.org/abs/1704.01212) model.
Ref. #300
__Progress__
---
> Implement MPNN model

- chainer_chemistry/links/update/ggnn_update.py
- chainer_chemistry/models/__init__.py
- chainer_chemistry/models/ggnn.py
- chainer_chemistry/utils/__init__.py
- chainer_chemistry/utils/sparse_utils.py
- tests/links_tests/update_tests/test_ggnn_update.py
- tests/models_tests/test_ggnn.py
- tests/utils_tests/test_sparse_utils.py
This PR adds new implementation: GGNN for sparse matrix inputs.
* I slightly modified the implementation of `GGNNUpdater`. Now the updater can accept `CooMatrix` as well as dense `ndarray`.
* The original `GGNN` is unchanged.
* `SparseGGNN` is newly introduced.
* Several tests are added.
> Implement SparseGGNN

- chainer_chemistry/links/array/shape_transformer_2d.py
- chainer_chemistry/links/array/shape_transformer_to_2d.py
- chainer_chemistry/links/scaler/standard_scaler.py
- tests/links_tests/array_tests/test_shape_transformer_2d.py
- tests/links_tests/array_tests/test_shape_transformer_to_2d.py
- tests/links_tests/scaler_tests/test_standard_scaler.py
StandardScaler with more than 3-dim array
> Scaler axis

- chainer_chemistry/links/array/shape_transformer_2d.py
- chainer_chemistry/links/scaler/max_abs_scaler.py
- chainer_chemistry/links/scaler/standard_scaler.py
- tests/links_tests/array_tests/test_shape_transformer_2d.py
- tests/links_tests/scaler_tests/test_max_abs_scaler.py
- tests/links_tests/scaler_tests/test_standard_scaler.py
> Max abs scaler

- chainer_chemistry/links/array/shape_transformer_2d.py
- chainer_chemistry/links/scaler/min_max_scaler.py
- chainer_chemistry/links/scaler/standard_scaler.py
- tests/links_tests/array_tests/test_shape_transformer_2d.py
- tests/links_tests/scaler_tests/test_min_max_scaler.py
- tests/links_tests/scaler_tests/test_standard_scaler.py
> Min max scaler

- chainer_chemistry/dataset/preprocessors/weavenet_preprocessor.py
- tests/dataset_tests/preprocessors_tests/test_weavenet_preprocessor.py
Preprocessor did not work when num_max_atoms are specified (other than default value).
> Bug fix: Weave preprocessor

- chainer_chemistry/models/prediction/graph_conv_predictor.py
- examples/molnet/predict_molnet.py
- examples/molnet/train_molnet.py
- examples/own_dataset/predict_own_dataset.py
- examples/own_dataset/train_own_dataset.py
- examples/qm9/predict_qm9.py
- examples/qm9/train_qm9.py
Use label_scaler.inverse_transform for both train/predict
It makes code very easy to understand.
Computational time for always postprocess `inverse_transform` is quite small and i think this is acceptable.
> use label_scaler

- .flexci/config.pbtxt
- .flexci/gen_config.py
- .flexci/pytest_script.sh
- docker/conda/python36/Dockerfile
- docker/conda/python37-chainerx-cpu-base/Dockerfile
- docker/conda/python37-chainerx-cpu-base/conda-entrypoint.sh
- docker/conda/python37-chainerx-cpu-latest/Dockerfile
- docker/conda/python37-chainerx-cpu-latest/conda-entrypoint.sh
- docker/conda/python37-chainerx-cpu-stable/Dockerfile
- docker/conda/python37-chainerx-cpu-stable/conda-entrypoint.sh
- docker/conda/python37-chainerx-gpu-base/Dockerfile
- docker/conda/python37-chainerx-gpu-base/conda-entrypoint.sh
- docker/conda/python37-chainerx-gpu-latest/Dockerfile
- docker/conda/python37-chainerx-gpu-latest/conda-entrypoint.sh
- docker/conda/python37-chainerx-gpu-stable/Dockerfile
- docker/conda/python37-chainerx-gpu-stable/conda-entrypoint.sh
- docker/conda/python37/Dockerfile
- tests/links_tests/readout_tests/test_mpnn_readout.py
- tests/links_tests/update_tests/test_relgcn_update.py
- tests/models_tests/test_mpnn.py
Resolve #380 
After this PR, we support below environments.
* Python 3.6, 3.7
* RDKit 2019.03.4.0
* chainer v6.0.0, stable, latest
* cupy v6.0.0, stable, latest
* use chainerx or not
* use gpu or not
> New Flexci test environment

- chainer_chemistry/utils/__init__.py
- chainer_chemistry/utils/train_utils.py
- examples/molnet/train_molnet.py
- examples/own_dataset/train_own_dataset.py
- examples/qm9/train_qm9.py
- examples/tox21/train_tox21.py
- tests/models_tests/gwm_tests/test_gwm.py
- tests/utils_tests/test_train_utils.py
Introduced `run_train` util method. It can be used for typical training.
> Train utils

- chainer_chemistry/dataset/networkx_preprocessors/reddit_coo.py
- chainer_chemistry/datasets/citation_network/citation.py
- chainer_chemistry/datasets/citation_network/citeseer.py
- chainer_chemistry/datasets/citation_network/cora.py
- chainer_chemistry/datasets/reddit/reddit.py
- examples/network_graph/README.md
- examples/network_graph/train_network_graph.py
Support automatic data download.
Please try running code under `examples/network_graph`
```
python train_network_graph.py --dataset cora --method gin --device 0
python train_network_graph.py --dataset citeseer --method gin_sparse --device 0
python train_network_graph.py --dataset reddit --device 0 --method gin --coo true
```
> Chainer graph refactor

- examples/molnet_wle/predict_molnet_wle.py
- examples/molnet_wle/train_molnet_wle.py
* Fix train_molnet_wle.py: dictionary key setting 
* FIx predict_molnet_wle.py: import error
> Fix errors for RSGCN-CWLE/GWLE
