chainer/chainer-chemistry

examples/tox21/predictor.py
This PR fixes #38.
We change a device to which minibatches are transferred in an inference loop depending on where a predictors is located.
=> Fix InferenceLoop.inference to support computation in GPU in the Tox21 example.

.readthedocs.yml, docs/source/environment.yml, docs/source/requirements.txt
Fix #48 
To generate documents properly, we need installing RDKit.
So I wrote some settings for installing RDKit in readthedocs environment.
The result is [here](http://chainer-chemistry-test.readthedocs.io/en/fixdocs/dataset.html)
=> Fix readthedocs setting

.travis.yml
This PR changes `.travis.yml` to test if Chainer Chemistry work with Chainer v2.
=> Test Python 3.5 and Chainer v2, v4pre in Travis

examples/example_test_cpu.sh, examples/example_test_gpu.sh, examples/tox21/inference_tox21.py
This PR fixes #67 by using a snapshot specified by `--trainer-snapshot` if it is not empty. I also change the testing scripts for examples to check this option.
=> Use --trainer-snapshot option of Tox21

examples/qm9/README.md
We write dependency on `scikit-learn` of the QM9 example explicitly to its README.
=> Write dependency on sklearn to the README of the QM9 example

docs/source/conf.py
This PR adds [napoleon](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html#) to `conf.py`. It is a Sphinx extension that enables us to write documents following Google Python Style Guide. As some of our documents are written in this style, we need to include it.
=> Include napoleon as an extension

.readthedocs.yml, docs/source/environment.yml, docs/source/requirements.txt
This pull request solves build failure of readthedocs.
It is caused by cupy build error in RTD environment and dependency on scikit-learn. Scikit-learn depends on Scipy.
=> Fix some dependencies for rtd

tests/datasets_tests/test_tox21.py
It should delete tox21 files not qm9 ones in this context.
=> Fix test_get_tox21_filepath_with_download

examples/tox21/README.md
=> Remove typo from examples/tox21/README.md

chainer_chemistry/dataset/parsers/csv_file_parser.py, chainer_chemistry/dataset/parsers/sdf_file_parser.py, chainer_chemistry/datasets/qm9.py, chainer_chemistry/datasets/tox21.py, tests/dataset_tests/parsers_tests/test_sdf_file_parser.py
Originally smiles is returned as `list` with `get_qm9` or `get_tox21` method.
However this PR is to change its type to return `numpy array`.
The motivation is that since dataset features are of numpy array, I felt it is more unified when numpy array is returned.
Also, advanced indexing can be used when the type is numpy array instead of `list`
However since `list` type was originally returned, **this PR breaks backward compatibility** while I guess the effect is small (because there is no example code to use `retain_smiles=True` for now.
=> return smiles as numpy array

chainer_chemistry/iterators/balanced_serial_iterator.py
This PR fixes the document of `BalancedSerialIterator`. Specifically, it
- removes incomplete documents temporarily.
- moves documents on an internal value of `_previous_epoch_detail` to comments of `previous_epoch_detail`, as it is about internal implementation and may not be appropriate to be treated as specification.
- adds documents on the cases when `shuffle` and `batch_balancing` options being undocumented values.
=> Enhance documents of BalancedSerialIterator

setup.py
Issue: https://github.com/pfnet-research/chainer-chemistry/issues/82
scikit-learn does not install scipy automatically, so we explicitly include scipy as dependency.
=> Add scipy in dependency

chainer_chemistry/models/prediction/__init__.py, chainer_chemistry/models/prediction/base.py, chainer_chemistry/models/prediction/classifier.py, chainer_chemistry/models/prediction/regressor.py
Introduce BaseForwardModel 
1. to commonize `_forward` method
2. introduce `_device` management
user can update device of model by `update_device` method.
This PR also resolves https://github.com/pfnet-research/chainer-chemistry/issues/134
=> [refactor] Introduce BaseForwardModel

docs/source/development.rst
This PR add a paragraph on portability of `BaseForwardModel` to the development policy. We should not merge this PR unless #139 is merged, as the comment is about features introduced in the PR. For that reason, we may want to send this PR to #139 (how do you think? @corochann).
=> Add a comment on model portability to the development policy

chainer_chemistry/models/rsgcn.py, tests/models_tests/test_rsgcn.py
- Adding `dropout_ratio` attribute to control dropout ratio in RSGCN.
- Added a test for RSGCN
- forward
- backward
- graph isomorphism invariant
=> Test rsgcn

examples/qm9/predict_qm9.py, examples/qm9/train_qm9.py, examples/tox21/predict_tox21_with_classifier.py, examples/tox21/train_tox21.py
This PR changes the Tox21 and QM9 examples to skip availability of `Classifier`.
Currently, code in the Tox21 and QM9 examples check if `Classifier` is available because previously the version we can install via pip was v0.2.0, where `Classifier` is not available. Now we can get v0.3.0 with pip, we do not need this conditioning.
=> Remove conditional import of Classifier

tests/datasets_tests/molnet_tests/test_molnet.py
There are two tests named`test_get_molnet_clearance_dataset` in a file. So, either of them is not tested. This PR renames one of them.
=> Rename duplicated test name

chainer_chemistry/functions/__init__.py, chainer_chemistry/functions/mean_squared_error.py, docs/source/functions.rst, tests/functions_tests/test_mean_squared_error.py
=> mean_squared_error with `ignore_nan` option

setup.py
This PR changes to retrieve the version number of Chainer Chemistry in setup.py without using imp. Essentially same change as https://github.com/chainer/chainer/pull/4846
=> Retrieve version number in setup.py without imp

chainer_chemistry/dataset/indexer.py, chainer_chemistry/datasets/numpy_tuple_dataset.py, tests/dataset_tests/test_numpy_tuple_feature_indexer.py, tests/datasets_tests/test_numpy_tuple_dataset.py
This PR contains non compatibility change.
=> Fix indexing behavior in NumpyTupleDataset

chainer_chemistry/training/extensions/__init__.py, chainer_chemistry/training/extensions/batch_evaluator.py, chainer_chemistry/training/extensions/prc_auc_evaluator.py, chainer_chemistry/training/extensions/roc_auc_evaluator.py, tests/training_tests/extensions_tests/test_prc_auc_evaluator.py
=> Implement PRCAUCEvaluator

examples/tox21/README.md
This PR removes description about `inference_tox21.py` from `README.md` of the Tox21 example, as it has been already removed.
=> Remove description about inference_tox21.py

.travis.yml
Many many errors are happened recently in Travis CI. This PR explore why it is happened.
=> Change RDKit version in Travis CI Test

README.md
resolves https://github.com/pfnet-research/chainer-chemistry/issues/192 and https://github.com/pfnet-research/chainer-chemistry/issues/231
=> Fix library version support

.travis.yml
This PR changes `.travis.yaml` to invoke all CPU tests including slow and example everyday in Travis CI.
=> Daily test

chainer_chemistry/functions/__init__.py, chainer_chemistry/functions/r2_score.py, chainer_chemistry/training/extensions/__init__.py, chainer_chemistry/training/extensions/r2_score_evaluator.py, tests/functions_tests/test_r2_score.py, tests/training_tests/extensions_tests/test_r2_score_evaluator.py
Implement R2 score function to evaluate PDBbind dataset
=> Add R2 score function

examples/qm9/evaluate_models_qm9.sh, examples/qm9/predict_qm9.py, examples/qm9/test_qm9.sh, examples/qm9/train_qm9.py
@mottodora Can you please review?
=> Scale output labels in the QM9 example and refactor code.

chainer_chemistry/dataset/preprocessors/common.py, chainer_chemistry/dataset/preprocessors/ggnn_preprocessor.py, chainer_chemistry/utils/extend.py, tests/dataset_tests/preprocessor_tests/test_common.py
Please merge after https://github.com/pfnet-research/chainer-chemistry/pull/260
This PR construct discrete edge matrix in O(E), instead of O(N^2)
I checked the time difference in this kind of code
```
from rdkit import Chem
from chainer_chemistry.dataset.preprocessors import common
from contextlib import contextmanager
from time import time, perf_counter
@contextmanager
def timer(name):
t0 = perf_counter()
yield
t1 = perf_counter()
print('[{}] done in {:.6f} ms'.format(name, (t1-t0) * 1000))
num_atoms_list = [10, 100, 1000]
for num_atoms in num_atoms_list:
mol = Chem.MolFromSmiles('C' * num_atoms)
with timer('num_atoms {}'.format(num_atoms)):
common.construct_discrete_edge_matrix(mol)
```
Results:
- Before this PR
```
[num_atoms 10] done in 0.166040 ms
[num_atoms 100] done in 4.342746 ms …
```
=> Construct discrete edge matrix fast

chainer_chemistry/models/prediction/classifier.py, chainer_chemistry/models/prediction/regressor.py
resolves https://github.com/pfnet-research/chainer-chemistry/issues/289
Metrics function can return normal array instead of Variable, so `self._convert_to_scalar(value(self.y, t).data` is not ok (when the returned value is array, `.data` refer memoryview instead of actual value).
=> bug fix: consider the case when metrics returns non-Variable case.

chainer_chemistry/links/readout/nfp_readout.py, chainer_chemistry/links/update/nfp_update.py, chainer_chemistry/models/nfp.py, tests/models_tests/test_nfp.py
take over from https://github.com/pfnet-research/chainer-chemistry/pull/228
when is_real_node passed, we can calculate the output value ignoring the effect from virtual node.
=> NFP input size invariant: add is_real_node argument

chainer_chemistry/links/__init__.py, chainer_chemistry/links/scaler/base.py, chainer_chemistry/links/scaler/standard_scaler.py, tests/links_tests/scaler_tests/test_standard_scaler.py
StandardScaler with chainer.Link
there are several benefits:
- serialization inside chainer.Chain
- gpu calculation support
- only scale `indices`, if specified.
=> Standard scaler link

examples/molnet/train_molnet.py, examples/own_dataset/train_own_dataset.py, examples/qm9/train_qm9.py, examples/tox21/predictor.py
=> use mlp for relgcn

setup.py
This PR enables 'Type Hints' with python2.7.
You do not have to write 'Type Hints' for all scripts but it is better if you can.
=> Add typing module

chainer_chemistry/links/scaler/base.py, tests/links_tests/scaler_tests/test_standard_scaler.py
This PR supports to use `__call__` method for scalers.
- It makes possible to use this kind of API.
```
scaler = StandardScaler()
scaler.fit(x)
...
x_scaled = scaler(x)
```
- Also, chainer.Sequential uses `__call__` method, so we can use Sequential as follows,
```
from chainer import Sequential
model_with_scaler = Sequential(scaler, model)
```
=> scaler forward, __call__ support

chainer_chemistry/links/scaler/max_abs_scaler.py, chainer_chemistry/links/scaler/min_max_scaler.py, chainer_chemistry/saliency/visualizer/__init__.py, chainer_chemistry/saliency/visualizer/mol_visualizer.py, tests/saliency_tests/visualizer_tests/test_mol_visualizer.py
I'm sorry I did not check my folk is latest or not.
This is some fix typo.
MolVisualier -> MolVisualizer
shape_transformer_2d ->shape_transformer_to_2d
ShapeTransformer2D -> ShapeTransformerTo2D
=> fix typo MolVisualier, shape_transformer_2d

chainer_chemistry/datasets/numpy_tuple_dataset.py
numpy changed its default value from version 1.16.2, we need to explicitly set `allow_pickle=True` to load object type.
=> allow_pickle=True

docker/python3/Dockerfile
File creations and deletions moved to same layer to reduce size.
Achieved the image size reduction of 270MB.
```
$ docker image ls |grep chainer-chemistry
chainer-chemistry           modified            1234567890        18 minutes ago      4.59GB
chainer-chemistry           latest              0987654321        About an hour ago   4.86GB
```
=> Reduce container image size

chainer_chemistry/dataset/preprocessors/common.py, chainer_chemistry/models/gwm.py, tests/dataset_tests/preprocessor_tests/test_common.py, tests/models_tests/test_gwm.py
=> Refactoring Graph Warp Module

docker/python3/Dockerfile
Change to specify pandas version, since latest pandas doesn't support python3.5.2 which is installed for ubuntu 16.04.
`ldconfig` is required to import rdkit.
=> fix pandas and rdkit import error on Docker

tests/links_tests/scaler_tests/test_flow_scaler.py
test_flow_scaler takes time because it internally trains model inside `fit` method.
This PR adds "slow" flag to skip test for CI.
Instead I added simple test to only check to run each method.
=> add mark.slow flag in test_flow_scaler

chainer_chemistry/functions/__init__.py, chainer_chemistry/functions/activation/shifted_softplus.py, chainer_chemistry/links/readout/schnet_readout.py, chainer_chemistry/links/update/schnet_update.py, result/log, tests/functions_tests/activation/test_shifted_softplus.py
Add shifted-softplus for SchNet for stability
Add test of shifted softplus
before
```
epoch       main/loss   main/mae    main/rmse   validation/main/loss  validation/main/mae  validation/main/rmse  elapsed_time
1           9.16072e+07  4635.03     5493.88     2.04751e+06           1172.89              1430.77               4.68606       
2           736497      626.273     809.699     175424                307.404              418.077               8.61846       
3           111058      246.223     331.111     83034.3               203.431              286.713               12.6977       
...
20          8439.32     56.8124     90.6312     9510.97               55.5326              92.7485               81.2714       
```
after
```
epoch       main/loss   main/mae    main/rmse …
```
=> add shifted softplus

chainer_chemistry/functions/activation/shifted_softplus.py
I think `chainer.as_variable` is better choice here because it throws a descriptive error if `x` cannot be treated as an array.
=> Use as_variable instead of isinstance

setup.py
We don't support python2 and it has difficulty in installing in python3.7.
=> Remove typing dependency
